openapi: 3.0.3
info:
  title: Task Manager API
  description: API for managing Tasks
  version: 1.0.0

servers: 
  - url: http://localhost:5001/api
    description: API server for task manager

paths:
  /tasks:
    post:
      summary: Create a task
      tags: [Task manager]
      requestBody:
        required: true
        content: 
          application/json:
            schema: 
              $ref: '#/components/schemas/TaskInput'
      responses:
        '201': 
          description: Task was created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

    get:
      summary: Fetch every task
      tags: [Task manager]
      responses:
        '200': 
          description: All tasks are fetched from the database
          content: 
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Task'

  /tasks/{id}:
    get: 
      summary: Fetch task with specific id
      tags: [Task manager]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
    put:
      summary: Update the task
      tags: [Task manager]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
      responses:
        '200':
          description: Task updated
    delete:
      summary: Delete the task
      tags: [Task manager]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Task deleted 
        '404':
          description: Task not found

components:
  schemas: 
    Task:
      type: object
      properties:
        id: 
          type: string
          example: A123BE
        title:
          type: string
          example: Grocery shopping
        description: 
          type: string
          example: Finish your homework
        status:
          type: string
          default: 'pending'
          enum: ['pending', 'in-progress', 'completed']
          example: 'in-progress'
        dueDate: 
          type: string
          format: date-time
          example: '2025-09-01T12:00:00Z'
        createdAt: 
          type: string
          format: date-time
          example: '2025-09-01T10:00:00Z'

    TaskInput:
      type: object
      properties:
        title:
          type: string
        description: 
          type: string
        status:
          type: string
          default: 'pending'
          enum: ['pending', 'in-progress', 'completed']
        dueDate: 
          type: string
          format: date-time
      required:
        - title
