openapi: 3.0.3
info:
  title: My API
  description: A brief description of your API
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /recipes:
    get:
        summary: Get all recipes
        responses:
          '200':
            description: Successful response
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string

  /example:
    get:
      summary: Retrieve example data
      description: Returns example data from the API
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Resource not found"

    post:
      summary: Create example data
      description: Sends example data to the API
      requestBody:
        description: Data to create
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        '201':
          description: Resource created successfully
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid request body"

components:
  schemas:
    GenericObject:
      type: object
      additionalProperties: true
