name: CD - Docker Setup for Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and start services
        run: docker-compose -f docker-compose.yml up --build -d

      - name: Run tests inside container
        run: docker-compose -f docker-compose.yml exec api npm test

      - name: Push API image
        run: docker-compose -f docker-compose.yml push api
