name: CI/CD Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0   # Docker image for MongoDB
        ports:
          - 27017:27017
        options: > 
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'" 
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Wait for MongoDB to be ready
        run: |
          until mongo --eval "print(\"MongoDB is ready\")"; do
            echo "Waiting for MongoDB..."
            sleep 5
          done
          sleep 5  # Extra wait time to ensure MongoDB is fully ready

      - name: Start Task Tracker API
        working-directory: ./smallProjects/task_tracker_api
        run: /
          node server.js &
          sleep 10

      - name: Start Recipe Manager API
        working-directory: ./smallProjects/recipe_manager_api
        run: /
          node server.js &
          sleep 10

      - name: Run Task Tracker API tests with Newman
        working-directory: ./smallProjects/task_tracker_api
        run: |
          npm install -g newman
          newman run postman/Task_tracker.postman_collection.json \ --environment postman/local.postman_environment.json

      - name: Run Recipe Manager API tests with Newman
        working-directory: ./smallProjects/recipe_manager_api
        run: |
          npm install -g newman
          newman run postman/Recipe_Manager.postman_collection.json
          newman run postman/Recipe_Manager_error_handling.postman_collection.json