name: CI/CD Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongo:
        image: mongo:5.0
        ports: ['27017:27017']
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Wait for MongoDB port to be ready
      - name: Wait for MongoDB
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat-openbsd
          until nc -z localhost 27017; do
            echo "Waiting for MongoDB..."
            sleep 2
          done

      - name: Install Recipe Manager dependencies
        working-directory: ./smallProjects/recipe_manager_api
        run: npm install

      - name: Start Recipe Manager API
        working-directory: ./smallProjects/recipe_manager_api
        run: |
          PORT=5000 node server.js > server.log 2>&1 &

      - name: Debug Recipe Manager API startup
        working-directory: ./smallProjects/recipe_manager_api
        run: |
          sleep 5
          cat server.log

      - name: Wait for Recipe Manager API
        working-directory: ./smallProjects/recipe_manager_api
        run: |
          npx wait-on --timeout 60000 http://localhost:5000/api/health

      # Task Tracker API
      - name: Install Task Tracker dependencies
        working-directory: ./smallProjects/task_tracker_api
        run: npm install
          node server.js > server.log 2>&1 & 
          sleep 5
          cat server.log
          npx wait-on --timeout 60000 http://localhost:5001/api/health

      # Recipe Manager API
      

      # Run API tests
      - name: Run Task Tracker API tests with Newman
        working-directory: ./smallProjects/task_tracker_api
        run: |
          npm install newman
          npx newman run postman/Task_tracker.postman_collection.json \
            --environment postman/local.postman_environment.json

      - name: Run Recipe Manager API tests with Newman
        working-directory: ./smallProjects/recipe_manager_api
        run: |
          npm install newman
          npx newman run postman/Recipe_Manager.postman_collection.json
          npx newman run postman/Recipe_Manager_error_handling.postman_collection.json
